### ISSUE TITLE
[Issue]No UTF support

### ISSUE THREAD

**Issue by MatejMecka** [JuanPotato/Netflix-Activity-Scraper#1]
There isn't UTF-8 support and you can get errors about it!

**Comment by JuanPotato** [comment]
Could you give me an example of when this happens and possibly explain it better

**Comment by ManveerBasra** [comment]
Consider this episode of Breaking Bad (notice the á):
`Breaking Bad: Season 3: "No Más"`
If you don't have UTF-8 support it will most likely output as:
`Breaking Bad: Season 3: "No M?s".`

That is what happened in my [get_netflix_activity](https://github.com/ManveerBasra/get_netflix_activity) however the issue was resolved.

**Comment by JuanPotato** [comment]
Weird, I'm able to display characters like `ó` in title's no problem. They just go through the script. Would you mind running the updated script? Also if you are running python 2 that may be the problem.

**Comment by ManveerBasra** [comment]
I didn't run the actual program was just clarifying what @MatejMecka wrote

**Comment by JuanPotato** [comment]
It's fine, would you mind testing it though? The more people that try it the better.

**Comment by ManveerBasra** [comment]
got this error when I tried running
`Traceback (most recent call last):`
  `File "C:/Users/Manveer Singh/Documents/GitHub/Netflix-Activity-Scraper/netflix.py", line 125, in <module>`
    `user = NetflixSession(email, password)`
  `File "C:/Users/Manveer Singh/Documents/GitHub/Netflix-Activity-Scraper/netflix.py", line 29, in __init__`
    `soup = BeautifulSoup(page.text, 'lxml')`
  `File "C:\Python35\lib\site-packages\bs4\__init__.py", line 165, in __init__`
    `% ",".join(features))`
`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`

Would it be possible to create a setup.txt to let the user know what to install?

**Comment by ManveerBasra** [comment]
In your last `while` loop, you define a variable named `index` in the `try` block and try to access the same variable in your `except` block. You're trying to access `index` from outside it's scope. A solution could be to define `index` before the `try` statement so the variable's scope includes both the `try` and `except` blocks

**Comment by ManveerBasra** [comment]
I'll edit and create a pull request

**Comment by JuanPotato** [comment]
@ManveerBasra I'd rather create a more elegant solution rather than a text file telling people what to install. I'll come back to it tomorrow and see what there is, feel free to make a PR for something other better than a setup.txt in the meantime. Maybe improving Readme
